### ISSUE TITLE
Add ability to specify docker-remote configuration values in docker-compose.yml

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/docker-remote#5]
The docker-compose file format allows for extension fields that can be of any structure as long as they are prefixed with `x-` and located at the root of the file. We could use this to allow users to set docker-remote options in that file, eg.:

```yaml
version: '3'
services:
  web:
    image: nginx
x-docker-remote:
  project:
    name: myapp
  remote:
    host: myhost.com
    user: docker-remote
  tunnel:
    remote_user: root
```
